### ISSUE TITLE
URL for X11 intent is not generated correctly

### ISSUE THREAD

**Issue by nitomartinez** [openintents/openintents.github.io#4]
The URI for the X11 intent seems to point to the wrong place.

Currently it points to:

http://www.openintents.org/action/android-intent-action-view/

which does not match the spec.

Reviewing other examples, this is (just guessing), probably due to the fact that I am not using any particular action besides: "android.intent.action.VIEW"

Could this be?

Do I need to make any changes to the X11.md file?

Thanks for your efforts,

Nito

**Comment by friedger** [comment]
Currently, the intent registry is set up to have just one specification per action, in this case android.intent.action.VIEW.

In addition x11 is used for startService instead of startActivity.

Furthermore, startService must not used with implicit intents. This means more work needed on the whole setup.

**Comment by nitomartinez** [comment]
thanks for coming back.

X11 is nomally used with startActivity, (at least all the current implementations support that). Let me correct the example, as it is outdated. Thanks for pointing that out.

What would be really useful is to have a URL like this

http://www.openintents.org/action/com-google-android-radar-show-radar/

So that it can be shared by the three projects (and others that might use it).

Not sure if I need to do any changes here in this case, or help with this.

Again, thanks for the support and the idea of openintents.

**Comment by friedger** [comment]
Oh, I see, I have changed the registry to make it work as http://www.openintents.org/service/x11-server

You can change it back from service to an activity by removing the component line.

The permalink property overwrites the default link (action/"action_name").

If I understand correctly this is a specialisation of the view action, so what about this:
http://www.openintents.org/action/android-intent-action-view/x11-server

**Comment by nitomartinez** [comment]
that sounds perfect.

For me that is a good solution. Happy to close the issue.

**Comment by friedger** [comment]
Fixed by 8177218777406d23ce1955766a8a77cb7206a398 and 803277b61ddcae3bbe6e844a218638b7cfbc5ef4
